# Generated by Django 4.0.4 on 2022-04-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0005_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantite_add', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=12, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tags_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=12, default=0, max_digits=15)),
                ('etoile', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='commerce.tags_products')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.vendeur')),
            ],
        ),
    ]
