# Generated by Django 4.0.4 on 2022-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
