# Generated by Django 4.0.4 on 2022-05-13 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
