# Generated by Django 4.0.4 on 2022-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug_alter_post_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='post/images'),
            preserve_default=False,
        ),
    ]
