# Generated by Django 4.0.4 on 2022-04-23 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_type_vendeur_achetteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achetteur',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/Vendeur/images'),
        ),
        migrations.AlterField(
            model_name='achetteur',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/Vendeur/images'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
