# Generated by Django 4.0.4 on 2022-04-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_achetteur_profile_alter_achetteur_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achetteur',
            name='type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='type',
        ),
    ]
