# Generated by Django 4.0.4 on 2022-04-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_achetteur_type_remove_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('VENDEUR', 'Vendeur'), ('ACHETTEUR', 'Achetteur'), ('VISITEUR', 'Visiteur')], default='VISITEUR', max_length=255),
        ),
    ]
