# Generated by Django 4.0.4 on 2022-04-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_member_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationalite',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
