# Generated by Django 4.0.4 on 2022-04-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_user_nationalite_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
