# Generated by Django 4.0.4 on 2022-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_user_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achetteur',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='couvertures/images'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/images'),
        ),
    ]
