# Generated by Django 4.0.4 on 2022-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_remove_achetteur_profile_remove_member_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
