# Generated by Django 4.0.4 on 2022-05-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_visiteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='profile',
        ),
        migrations.AddField(
            model_name='vendeur',
            name='Ville',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
