# Generated by Django 4.0.4 on 2022-05-17 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_remove_vendeur_profile_vendeur_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visiteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
