# Generated by Django 4.0.4 on 2022-05-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_alter_vendeur_user_alter_visiteur_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendeur',
            old_name='Ville',
            new_name='ville',
        ),
    ]
